Calendar課題
siroemk/ruby-practices pull request #2
Opened 2021-02-01 04:12 UTC by siroemk

Calendar課題のコードを作成しました。
ご確認をお願いします。

- オプションなしで今月のカレンダー（今日の日付の色反転あり）
- ``-m``オプションで月の指定。``-y``オプションで年の指定。
- ``-h``オプションで今日の日付の色反転なし

2021-02-04 14:13 UTC, u1tnk requested changes

2021-02-04 14:13 UTC, u1tnk commented on 02.calendar/cal.rb
> +today_color = "\e[7m#{today.day.to_s.rjust(2)}\e[0m"
歓迎要件ですね 👍 

`today_color` だと色情報のみが入ってそうなので文字列も入ってる変数名が良いですね。例えば`today_with_color` とか。

2021-02-04 14:13 UTC, u1tnk commented on 02.calendar/cal.rb
> +(first_day.wday * 3).times {print " "}
問題無いですが豆知識として
```
print " " * (first_day.wday * 3)
```

でも良いですね。rubyのかけ算は多機能なんですよねー ✨

2021-02-04 14:13 UTC, u1tnk commented on 02.calendar/cal.rb
> +  if day.saturday? && day == today && !params["h"]
ちょっと分岐条件が複雑になってますね。

- 行末(土曜)か？
- today かつ hオプション無しか？

の二種類なので何らかの方法で分けて判断するようにすればもう少し簡潔になると思います。
難しそうならヒント出すのでまずは考えてみてください 💪

2021-02-06 02:26 UTC, siroemk commented
@u1tnk 
ご確認いただき、ありがとうございます！
ご指摘いただいた箇所を修正しました。

- ``today_color``を``today_with_color``に変更
- 分岐条件を2つに分ける。``today かつ hオプション無し``でif式を書き、変数``display_date``に入れて、土曜日判定のif式で変数``display_date``を呼び出してみました。

2021-02-06 02:42 UTC, u1tnk commented on 02.calendar/cal.rb
> +  display_date =
良いですね 👍   かなり分かりやすくなりました。
人間、二つ以上の条件組み合わさったり、否定が混ざったりすると、結構読みづらいので、シンプルなものが複数ある形の方が読みやすくなるんですよね。
角谷さんのフォロー分かりやすかったですね。直接言わずにヒントにするの難しいです 😓 

ついでレベルなんで書いちゃうと `day.day.to_s.rjust(2)` が反転のところに二箇所あるのと、場所が分散してるので

```
display_date =day.day.to_s.rjust(2)
# 今日の日付は色を反転させる
display_date = "\e[7m#{display_date }\e[0m" if day == today && !params["h"]
```

このようにするともっとシンプルになりますよ。次回以降に役立ててください 💪

2021-02-06 02:48 UTC, u1tnk commented on 02.calendar/cal.rb
> +puts "\n"
あれ、問題は無いですが `puts` だと自動で改行もつくので、 `print "\n"` か `puts ""` で良いかと思います。
空文字なのも気持ち悪いので前者の方が良いと思いますが。

2021-02-06 06:34 UTC, merged